// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.2
// source: rpc_service.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ERROR_CODE int32

const (
	ERROR_CODE_OK                               ERROR_CODE = 0
	ERROR_CODE_EMPTY_NICKNAME                   ERROR_CODE = 1
	ERROR_CODE_DUP_NICKNAME                     ERROR_CODE = 2
	ERROR_CODE_NICKNAME_HAVE_SPECIAL_CHARACTERS ERROR_CODE = 3
	ERROR_CODE_UNABLE_TO_CREATE_USER            ERROR_CODE = 4
	ERROR_CODE_FAILED_TO_GET_USER               ERROR_CODE = 5
	ERROR_CODE_GOOGLE_AUTH_FAILED               ERROR_CODE = 6
	ERROR_CODE_EMPTY_ID_TOKEN                   ERROR_CODE = 7
	ERROR_CODE_FAILED_TO_UPDATE_LOGIN_KEY       ERROR_CODE = 8
	ERROR_CODE_FAILED_TO_CHANGE_LOGIN_TYPE      ERROR_CODE = 9
	ERROR_CODE_LOGIN_TYPE_IS_DIFFERENT          ERROR_CODE = 10
	ERROR_CODE_ACCESS_KEY_HAS_EXPIRED           ERROR_CODE = 11
	ERROR_CODE_SYSTME                           ERROR_CODE = 12
	ERROR_CODE_FAILED_TO_SAVE_ITEM              ERROR_CODE = 13
	ERROR_CODE_FAILED_TO_SAVE_MERCENARY         ERROR_CODE = 14
	ERROR_CODE_FAILED_TO_SAVE_STAGE             ERROR_CODE = 15
	ERROR_CODE_FAILED_TO_SAVE_UPGRADE_PLAYER    ERROR_CODE = 16
	ERROR_CODE_FAILED_TO_LOAD_ITEM              ERROR_CODE = 17
	ERROR_CODE_FAILED_TO_LOAD_MERCENARY         ERROR_CODE = 18
	ERROR_CODE_FAILED_TO_LOAD_STAGE             ERROR_CODE = 19
	ERROR_CODE_FAILED_TO_LOAD_UPGRADE_PLAYER    ERROR_CODE = 20
)

// Enum value maps for ERROR_CODE.
var (
	ERROR_CODE_name = map[int32]string{
		0:  "OK",
		1:  "EMPTY_NICKNAME",
		2:  "DUP_NICKNAME",
		3:  "NICKNAME_HAVE_SPECIAL_CHARACTERS",
		4:  "UNABLE_TO_CREATE_USER",
		5:  "FAILED_TO_GET_USER",
		6:  "GOOGLE_AUTH_FAILED",
		7:  "EMPTY_ID_TOKEN",
		8:  "FAILED_TO_UPDATE_LOGIN_KEY",
		9:  "FAILED_TO_CHANGE_LOGIN_TYPE",
		10: "LOGIN_TYPE_IS_DIFFERENT",
		11: "ACCESS_KEY_HAS_EXPIRED",
		12: "SYSTME",
		13: "FAILED_TO_SAVE_ITEM",
		14: "FAILED_TO_SAVE_MERCENARY",
		15: "FAILED_TO_SAVE_STAGE",
		16: "FAILED_TO_SAVE_UPGRADE_PLAYER",
		17: "FAILED_TO_LOAD_ITEM",
		18: "FAILED_TO_LOAD_MERCENARY",
		19: "FAILED_TO_LOAD_STAGE",
		20: "FAILED_TO_LOAD_UPGRADE_PLAYER",
	}
	ERROR_CODE_value = map[string]int32{
		"OK":                               0,
		"EMPTY_NICKNAME":                   1,
		"DUP_NICKNAME":                     2,
		"NICKNAME_HAVE_SPECIAL_CHARACTERS": 3,
		"UNABLE_TO_CREATE_USER":            4,
		"FAILED_TO_GET_USER":               5,
		"GOOGLE_AUTH_FAILED":               6,
		"EMPTY_ID_TOKEN":                   7,
		"FAILED_TO_UPDATE_LOGIN_KEY":       8,
		"FAILED_TO_CHANGE_LOGIN_TYPE":      9,
		"LOGIN_TYPE_IS_DIFFERENT":          10,
		"ACCESS_KEY_HAS_EXPIRED":           11,
		"SYSTME":                           12,
		"FAILED_TO_SAVE_ITEM":              13,
		"FAILED_TO_SAVE_MERCENARY":         14,
		"FAILED_TO_SAVE_STAGE":             15,
		"FAILED_TO_SAVE_UPGRADE_PLAYER":    16,
		"FAILED_TO_LOAD_ITEM":              17,
		"FAILED_TO_LOAD_MERCENARY":         18,
		"FAILED_TO_LOAD_STAGE":             19,
		"FAILED_TO_LOAD_UPGRADE_PLAYER":    20,
	}
)

func (x ERROR_CODE) Enum() *ERROR_CODE {
	p := new(ERROR_CODE)
	*p = x
	return p
}

func (x ERROR_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERROR_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_service_proto_enumTypes[0].Descriptor()
}

func (ERROR_CODE) Type() protoreflect.EnumType {
	return &file_rpc_service_proto_enumTypes[0]
}

func (x ERROR_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERROR_CODE.Descriptor instead.
func (ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{0}
}

type ITEM_TYPE int32

const (
	ITEM_TYPE_NONE            ITEM_TYPE = 0
	ITEM_TYPE_GOLD            ITEM_TYPE = 1000
	ITEM_TYPE_RUBY            ITEM_TYPE = 1001
	ITEM_TYPE_PIECE_KNIGHT    ITEM_TYPE = 1002
	ITEM_TYPE_PIECE_PIRATE    ITEM_TYPE = 1003
	ITEM_TYPE_PIECE_STAR      ITEM_TYPE = 1004
	ITEM_TYPE_PIECE_SCIENTIST ITEM_TYPE = 1005
	ITEM_TYPE_PIECE_STUDENT   ITEM_TYPE = 1006
)

// Enum value maps for ITEM_TYPE.
var (
	ITEM_TYPE_name = map[int32]string{
		0:    "NONE",
		1000: "GOLD",
		1001: "RUBY",
		1002: "PIECE_KNIGHT",
		1003: "PIECE_PIRATE",
		1004: "PIECE_STAR",
		1005: "PIECE_SCIENTIST",
		1006: "PIECE_STUDENT",
	}
	ITEM_TYPE_value = map[string]int32{
		"NONE":            0,
		"GOLD":            1000,
		"RUBY":            1001,
		"PIECE_KNIGHT":    1002,
		"PIECE_PIRATE":    1003,
		"PIECE_STAR":      1004,
		"PIECE_SCIENTIST": 1005,
		"PIECE_STUDENT":   1006,
	}
)

func (x ITEM_TYPE) Enum() *ITEM_TYPE {
	p := new(ITEM_TYPE)
	*p = x
	return p
}

func (x ITEM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ITEM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_service_proto_enumTypes[1].Descriptor()
}

func (ITEM_TYPE) Type() protoreflect.EnumType {
	return &file_rpc_service_proto_enumTypes[1]
}

func (x ITEM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ITEM_TYPE.Descriptor instead.
func (ITEM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{1}
}

type ITEM_CATEGORY int32

const (
	ITEM_CATEGORY_NORMAL   ITEM_CATEGORY = 0
	ITEM_CATEGORY_CURRENCY ITEM_CATEGORY = 1
)

// Enum value maps for ITEM_CATEGORY.
var (
	ITEM_CATEGORY_name = map[int32]string{
		0: "NORMAL",
		1: "CURRENCY",
	}
	ITEM_CATEGORY_value = map[string]int32{
		"NORMAL":   0,
		"CURRENCY": 1,
	}
)

func (x ITEM_CATEGORY) Enum() *ITEM_CATEGORY {
	p := new(ITEM_CATEGORY)
	*p = x
	return p
}

func (x ITEM_CATEGORY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ITEM_CATEGORY) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_service_proto_enumTypes[2].Descriptor()
}

func (ITEM_CATEGORY) Type() protoreflect.EnumType {
	return &file_rpc_service_proto_enumTypes[2]
}

func (x ITEM_CATEGORY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ITEM_CATEGORY.Descriptor instead.
func (ITEM_CATEGORY) EnumDescriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{2}
}

type LoginRequest_LOGIN_TYPE int32

const (
	LoginRequest_NON_CERT LoginRequest_LOGIN_TYPE = 0
	LoginRequest_GOOGLE   LoginRequest_LOGIN_TYPE = 1
	LoginRequest_FACEBOOK LoginRequest_LOGIN_TYPE = 2
)

// Enum value maps for LoginRequest_LOGIN_TYPE.
var (
	LoginRequest_LOGIN_TYPE_name = map[int32]string{
		0: "NON_CERT",
		1: "GOOGLE",
		2: "FACEBOOK",
	}
	LoginRequest_LOGIN_TYPE_value = map[string]int32{
		"NON_CERT": 0,
		"GOOGLE":   1,
		"FACEBOOK": 2,
	}
)

func (x LoginRequest_LOGIN_TYPE) Enum() *LoginRequest_LOGIN_TYPE {
	p := new(LoginRequest_LOGIN_TYPE)
	*p = x
	return p
}

func (x LoginRequest_LOGIN_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRequest_LOGIN_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_service_proto_enumTypes[3].Descriptor()
}

func (LoginRequest_LOGIN_TYPE) Type() protoreflect.EnumType {
	return &file_rpc_service_proto_enumTypes[3]
}

func (x LoginRequest_LOGIN_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRequest_LOGIN_TYPE.Descriptor instead.
func (LoginRequest_LOGIN_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{4, 0}
}

type RpcServiceExampleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg1 int32   `protobuf:"varint,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2 float32 `protobuf:"fixed32,2,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Arg3 string  `protobuf:"bytes,3,opt,name=arg3,proto3" json:"arg3,omitempty"`
	Arg4 bool    `protobuf:"varint,4,opt,name=arg4,proto3" json:"arg4,omitempty"`
	Arg5 []int32 `protobuf:"varint,5,rep,packed,name=arg5,proto3" json:"arg5,omitempty"`
}

func (x *RpcServiceExampleRequest) Reset() {
	*x = RpcServiceExampleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcServiceExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcServiceExampleRequest) ProtoMessage() {}

func (x *RpcServiceExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcServiceExampleRequest.ProtoReflect.Descriptor instead.
func (*RpcServiceExampleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *RpcServiceExampleRequest) GetArg1() int32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *RpcServiceExampleRequest) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *RpcServiceExampleRequest) GetArg3() string {
	if x != nil {
		return x.Arg3
	}
	return ""
}

func (x *RpcServiceExampleRequest) GetArg4() bool {
	if x != nil {
		return x.Arg4
	}
	return false
}

func (x *RpcServiceExampleRequest) GetArg5() []int32 {
	if x != nil {
		return x.Arg5
	}
	return nil
}

type RpcServiceExampleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error ERROR_CODE `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
}

func (x *RpcServiceExampleReply) Reset() {
	*x = RpcServiceExampleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcServiceExampleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcServiceExampleReply) ProtoMessage() {}

func (x *RpcServiceExampleReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcServiceExampleReply.ProtoReflect.Descriptor instead.
func (*RpcServiceExampleReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *RpcServiceExampleReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{2}
}

type PushNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PushNotification) Reset() {
	*x = PushNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotification) ProtoMessage() {}

func (x *PushNotification) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotification.ProtoReflect.Descriptor instead.
func (*PushNotification) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *PushNotification) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginType LoginRequest_LOGIN_TYPE `protobuf:"varint,1,opt,name=loginType,proto3,enum=msg.LoginRequest_LOGIN_TYPE" json:"loginType,omitempty"`
	LoginKey  string                  `protobuf:"bytes,2,opt,name=loginKey,proto3" json:"loginKey,omitempty"`
	IdToken   string                  `protobuf:"bytes,3,opt,name=idToken,proto3" json:"idToken,omitempty"`
	NickName  string                  `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetLoginType() LoginRequest_LOGIN_TYPE {
	if x != nil {
		return x.LoginType
	}
	return LoginRequest_NON_CERT
}

func (x *LoginRequest) GetLoginKey() string {
	if x != nil {
		return x.LoginKey
	}
	return ""
}

func (x *LoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *LoginRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     ERROR_CODE `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
	Usn       int32      `protobuf:"varint,2,opt,name=usn,proto3" json:"usn,omitempty"`
	NickName  string     `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	LoginKey  string     `protobuf:"bytes,4,opt,name=loginKey,proto3" json:"loginKey,omitempty"`
	AccessKey string     `protobuf:"bytes,5,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

func (x *LoginReply) GetUsn() int32 {
	if x != nil {
		return x.Usn
	}
	return 0
}

func (x *LoginReply) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *LoginReply) GetLoginKey() string {
	if x != nil {
		return x.LoginKey
	}
	return ""
}

func (x *LoginReply) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName     string        `protobuf:"bytes,1,opt,name=itemName,proto3" json:"itemName,omitempty"`
	ItemType     ITEM_TYPE     `protobuf:"varint,2,opt,name=itemType,proto3,enum=msg.ITEM_TYPE" json:"itemType,omitempty"`
	ItemCategory ITEM_CATEGORY `protobuf:"varint,3,opt,name=itemCategory,proto3,enum=msg.ITEM_CATEGORY" json:"itemCategory,omitempty"`
	ItemCount    int64         `protobuf:"varint,4,opt,name=itemCount,proto3" json:"itemCount,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Item) GetItemType() ITEM_TYPE {
	if x != nil {
		return x.ItemType
	}
	return ITEM_TYPE_NONE
}

func (x *Item) GetItemCategory() ITEM_CATEGORY {
	if x != nil {
		return x.ItemCategory
	}
	return ITEM_CATEGORY_NORMAL
}

func (x *Item) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type Mercenary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MercenaryName  string `protobuf:"bytes,1,opt,name=mercenaryName,proto3" json:"mercenaryName,omitempty"`
	MercenaryLevel int32  `protobuf:"varint,2,opt,name=mercenaryLevel,proto3" json:"mercenaryLevel,omitempty"`
}

func (x *Mercenary) Reset() {
	*x = Mercenary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mercenary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mercenary) ProtoMessage() {}

func (x *Mercenary) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mercenary.ProtoReflect.Descriptor instead.
func (*Mercenary) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *Mercenary) GetMercenaryName() string {
	if x != nil {
		return x.MercenaryName
	}
	return ""
}

func (x *Mercenary) GetMercenaryLevel() int32 {
	if x != nil {
		return x.MercenaryLevel
	}
	return 0
}

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageNum   int32 `protobuf:"varint,1,opt,name=stageNum,proto3" json:"stageNum,omitempty"`
	StageScore int64 `protobuf:"varint,2,opt,name=stageScore,proto3" json:"stageScore,omitempty"`
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *Stage) GetStageNum() int32 {
	if x != nil {
		return x.StageNum
	}
	return 0
}

func (x *Stage) GetStageScore() int64 {
	if x != nil {
		return x.StageScore
	}
	return 0
}

type UpgradePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PowerLevel        int32 `protobuf:"varint,1,opt,name=powerLevel,proto3" json:"powerLevel,omitempty"`
	AttackSpeedLevel  int32 `protobuf:"varint,2,opt,name=attackSpeedLevel,proto3" json:"attackSpeedLevel,omitempty"`
	CriticalLevel     int32 `protobuf:"varint,3,opt,name=criticalLevel,proto3" json:"criticalLevel,omitempty"`
	BuffDurationLevel int32 `protobuf:"varint,4,opt,name=buffDurationLevel,proto3" json:"buffDurationLevel,omitempty"`
	FreeCoinLevel     int32 `protobuf:"varint,5,opt,name=freeCoinLevel,proto3" json:"freeCoinLevel,omitempty"`
}

func (x *UpgradePlayer) Reset() {
	*x = UpgradePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePlayer) ProtoMessage() {}

func (x *UpgradePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePlayer.ProtoReflect.Descriptor instead.
func (*UpgradePlayer) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpgradePlayer) GetPowerLevel() int32 {
	if x != nil {
		return x.PowerLevel
	}
	return 0
}

func (x *UpgradePlayer) GetAttackSpeedLevel() int32 {
	if x != nil {
		return x.AttackSpeedLevel
	}
	return 0
}

func (x *UpgradePlayer) GetCriticalLevel() int32 {
	if x != nil {
		return x.CriticalLevel
	}
	return 0
}

func (x *UpgradePlayer) GetBuffDurationLevel() int32 {
	if x != nil {
		return x.BuffDurationLevel
	}
	return 0
}

func (x *UpgradePlayer) GetFreeCoinLevel() int32 {
	if x != nil {
		return x.FreeCoinLevel
	}
	return 0
}

type LoadGameDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadGameDataRequest) Reset() {
	*x = LoadGameDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadGameDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGameDataRequest) ProtoMessage() {}

func (x *LoadGameDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGameDataRequest.ProtoReflect.Descriptor instead.
func (*LoadGameDataRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{10}
}

type LoadGameDataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error         ERROR_CODE     `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
	Items         []*Item        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Mercenaries   []*Mercenary   `protobuf:"bytes,3,rep,name=mercenaries,proto3" json:"mercenaries,omitempty"`
	Stage         *Stage         `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	UpgradePlayer *UpgradePlayer `protobuf:"bytes,5,opt,name=upgradePlayer,proto3" json:"upgradePlayer,omitempty"`
}

func (x *LoadGameDataReply) Reset() {
	*x = LoadGameDataReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadGameDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGameDataReply) ProtoMessage() {}

func (x *LoadGameDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGameDataReply.ProtoReflect.Descriptor instead.
func (*LoadGameDataReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *LoadGameDataReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

func (x *LoadGameDataReply) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LoadGameDataReply) GetMercenaries() []*Mercenary {
	if x != nil {
		return x.Mercenaries
	}
	return nil
}

func (x *LoadGameDataReply) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *LoadGameDataReply) GetUpgradePlayer() *UpgradePlayer {
	if x != nil {
		return x.UpgradePlayer
	}
	return nil
}

type SaveGameDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items         []*Item        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Mercenaries   []*Mercenary   `protobuf:"bytes,3,rep,name=mercenaries,proto3" json:"mercenaries,omitempty"`
	Stage         *Stage         `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	UpgradePlayer *UpgradePlayer `protobuf:"bytes,5,opt,name=upgradePlayer,proto3" json:"upgradePlayer,omitempty"`
}

func (x *SaveGameDataRequest) Reset() {
	*x = SaveGameDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveGameDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameDataRequest) ProtoMessage() {}

func (x *SaveGameDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameDataRequest.ProtoReflect.Descriptor instead.
func (*SaveGameDataRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *SaveGameDataRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SaveGameDataRequest) GetMercenaries() []*Mercenary {
	if x != nil {
		return x.Mercenaries
	}
	return nil
}

func (x *SaveGameDataRequest) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *SaveGameDataRequest) GetUpgradePlayer() *UpgradePlayer {
	if x != nil {
		return x.UpgradePlayer
	}
	return nil
}

type SaveGameDataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error ERROR_CODE `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
}

func (x *SaveGameDataReply) Reset() {
	*x = SaveGameDataReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveGameDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameDataReply) ProtoMessage() {}

func (x *SaveGameDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameDataReply.ProtoReflect.Descriptor instead.
func (*SaveGameDataReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{13}
}

func (x *SaveGameDataReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

type RankingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int64 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *RankingRequest) Reset() {
	*x = RankingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingRequest) ProtoMessage() {}

func (x *RankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingRequest.ProtoReflect.Descriptor instead.
func (*RankingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{14}
}

func (x *RankingRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error ERROR_CODE `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
}

func (x *RankingReply) Reset() {
	*x = RankingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingReply) ProtoMessage() {}

func (x *RankingReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingReply.ProtoReflect.Descriptor instead.
func (*RankingReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{15}
}

func (x *RankingReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

type RankingListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RankingListRequest) Reset() {
	*x = RankingListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingListRequest) ProtoMessage() {}

func (x *RankingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingListRequest.ProtoReflect.Descriptor instead.
func (*RankingListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{16}
}

type RankingListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     ERROR_CODE                  `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ERROR_CODE" json:"error,omitempty"`
	MyRanking *RankingListReply_Ranking   `protobuf:"bytes,2,opt,name=myRanking,proto3" json:"myRanking,omitempty"`
	Rankings  []*RankingListReply_Ranking `protobuf:"bytes,3,rep,name=rankings,proto3" json:"rankings,omitempty"`
}

func (x *RankingListReply) Reset() {
	*x = RankingListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingListReply) ProtoMessage() {}

func (x *RankingListReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingListReply.ProtoReflect.Descriptor instead.
func (*RankingListReply) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{17}
}

func (x *RankingListReply) GetError() ERROR_CODE {
	if x != nil {
		return x.Error
	}
	return ERROR_CODE_OK
}

func (x *RankingListReply) GetMyRanking() *RankingListReply_Ranking {
	if x != nil {
		return x.MyRanking
	}
	return nil
}

func (x *RankingListReply) GetRankings() []*RankingListReply_Ranking {
	if x != nil {
		return x.Rankings
	}
	return nil
}

type RankingListReply_Ranking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Rank     int32  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Score    int32  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *RankingListReply_Ranking) Reset() {
	*x = RankingListReply_Ranking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankingListReply_Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingListReply_Ranking) ProtoMessage() {}

func (x *RankingListReply_Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingListReply_Ranking.ProtoReflect.Descriptor instead.
func (*RankingListReply_Ranking) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{17, 0}
}

func (x *RankingListReply_Ranking) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *RankingListReply_Ranking) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankingListReply_Ranking) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_rpc_service_proto protoreflect.FileDescriptor

var file_rpc_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x7e, 0x0a, 0x18, 0x52, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x33,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x35, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x35, 0x22, 0x3f, 0x0a, 0x16, 0x52, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x34, 0x0a, 0x0a, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x4f, 0x4e, 0x5f, 0x43, 0x45, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47,
	0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x41, 0x43, 0x45, 0x42,
	0x4f, 0x4f, 0x4b, 0x10, 0x02, 0x22, 0x9b, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x73, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4b, 0x65, 0x79, 0x22, 0xa4, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x52, 0x0c,
	0x69, 0x74, 0x65, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x09, 0x4d, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x43, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x0d, 0x55,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x10,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x70,
	0x65, 0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x69, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2c,
	0x0a, 0x11, 0x62, 0x75, 0x66, 0x66, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x62, 0x75, 0x66, 0x66, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d,
	0x66, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe9, 0x01, 0x0a, 0x11, 0x4c, 0x6f,
	0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x75,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0xc4, 0x01, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x30,
	0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0d, 0x75,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x11,
	0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x22, 0x35, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x82, 0x02,
	0x0a, 0x10, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x09, 0x6d, 0x79, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x6d, 0x79, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x39, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67,
	0x73, 0x1a, 0x4f, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x2a, 0xad, 0x04, 0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4d, 0x50,
	0x54, 0x59, 0x5f, 0x4e, 0x49, 0x43, 0x4b, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x44, 0x55, 0x50, 0x5f, 0x4e, 0x49, 0x43, 0x4b, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12,
	0x24, 0x0a, 0x20, 0x4e, 0x49, 0x43, 0x4b, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x48, 0x41, 0x56, 0x45,
	0x5f, 0x53, 0x50, 0x45, 0x43, 0x49, 0x41, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54,
	0x45, 0x52, 0x53, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x5f,
	0x54, 0x4f, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x47, 0x45,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x4f, 0x4f, 0x47,
	0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x06,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x5f, 0x49, 0x44, 0x5f, 0x54, 0x4f, 0x4b,
	0x45, 0x4e, 0x10, 0x07, 0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54,
	0x4f, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x4b,
	0x45, 0x59, 0x10, 0x08, 0x12, 0x1f, 0x0a, 0x1b, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54,
	0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x09, 0x12, 0x1b, 0x0a, 0x17, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x44, 0x49, 0x46, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x54,
	0x10, 0x0a, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4b, 0x45, 0x59,
	0x5f, 0x48, 0x41, 0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x0b, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x4d, 0x45, 0x10, 0x0c, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x49, 0x54, 0x45,
	0x4d, 0x10, 0x0d, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f,
	0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x4d, 0x45, 0x52, 0x43, 0x45, 0x4e, 0x41, 0x52, 0x59, 0x10,
	0x0e, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x53,
	0x41, 0x56, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x10, 0x0f, 0x12, 0x21, 0x0a, 0x1d, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x55, 0x50,
	0x47, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x10, 0x12, 0x17,
	0x0a, 0x13, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x4c, 0x4f, 0x41, 0x44,
	0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x11, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x4d, 0x45, 0x52, 0x43, 0x45, 0x4e,
	0x41, 0x52, 0x59, 0x10, 0x12, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f,
	0x54, 0x4f, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x10, 0x13, 0x12,
	0x21, 0x0a, 0x1d, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x5f, 0x4c, 0x4f, 0x41,
	0x44, 0x5f, 0x55, 0x50, 0x47, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x10, 0x14, 0x2a, 0x8c, 0x01, 0x0a, 0x09, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x04, 0x47, 0x4f,
	0x4c, 0x44, 0x10, 0xe8, 0x07, 0x12, 0x09, 0x0a, 0x04, 0x52, 0x55, 0x42, 0x59, 0x10, 0xe9, 0x07,
	0x12, 0x11, 0x0a, 0x0c, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x4b, 0x4e, 0x49, 0x47, 0x48, 0x54,
	0x10, 0xea, 0x07, 0x12, 0x11, 0x0a, 0x0c, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x50, 0x49, 0x52,
	0x41, 0x54, 0x45, 0x10, 0xeb, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x52, 0x10, 0xec, 0x07, 0x12, 0x14, 0x0a, 0x0f, 0x50, 0x49, 0x45, 0x43, 0x45,
	0x5f, 0x53, 0x43, 0x49, 0x45, 0x4e, 0x54, 0x49, 0x53, 0x54, 0x10, 0xed, 0x07, 0x12, 0x12, 0x0a,
	0x0d, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x55, 0x44, 0x45, 0x4e, 0x54, 0x10, 0xee,
	0x07, 0x2a, 0x29, 0x0a, 0x0d, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f,
	0x52, 0x59, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x43, 0x59, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_service_proto_rawDescOnce sync.Once
	file_rpc_service_proto_rawDescData = file_rpc_service_proto_rawDesc
)

func file_rpc_service_proto_rawDescGZIP() []byte {
	file_rpc_service_proto_rawDescOnce.Do(func() {
		file_rpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_service_proto_rawDescData)
	})
	return file_rpc_service_proto_rawDescData
}

var file_rpc_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_rpc_service_proto_goTypes = []interface{}{
	(ERROR_CODE)(0),                  // 0: msg.ERROR_CODE
	(ITEM_TYPE)(0),                   // 1: msg.ITEM_TYPE
	(ITEM_CATEGORY)(0),               // 2: msg.ITEM_CATEGORY
	(LoginRequest_LOGIN_TYPE)(0),     // 3: msg.LoginRequest.LOGIN_TYPE
	(*RpcServiceExampleRequest)(nil), // 4: msg.RpcServiceExampleRequest
	(*RpcServiceExampleReply)(nil),   // 5: msg.RpcServiceExampleReply
	(*Empty)(nil),                    // 6: msg.Empty
	(*PushNotification)(nil),         // 7: msg.PushNotification
	(*LoginRequest)(nil),             // 8: msg.LoginRequest
	(*LoginReply)(nil),               // 9: msg.LoginReply
	(*Item)(nil),                     // 10: msg.Item
	(*Mercenary)(nil),                // 11: msg.Mercenary
	(*Stage)(nil),                    // 12: msg.Stage
	(*UpgradePlayer)(nil),            // 13: msg.UpgradePlayer
	(*LoadGameDataRequest)(nil),      // 14: msg.LoadGameDataRequest
	(*LoadGameDataReply)(nil),        // 15: msg.LoadGameDataReply
	(*SaveGameDataRequest)(nil),      // 16: msg.SaveGameDataRequest
	(*SaveGameDataReply)(nil),        // 17: msg.SaveGameDataReply
	(*RankingRequest)(nil),           // 18: msg.RankingRequest
	(*RankingReply)(nil),             // 19: msg.RankingReply
	(*RankingListRequest)(nil),       // 20: msg.RankingListRequest
	(*RankingListReply)(nil),         // 21: msg.RankingListReply
	(*RankingListReply_Ranking)(nil), // 22: msg.RankingListReply.Ranking
}
var file_rpc_service_proto_depIdxs = []int32{
	0,  // 0: msg.RpcServiceExampleReply.error:type_name -> msg.ERROR_CODE
	3,  // 1: msg.LoginRequest.loginType:type_name -> msg.LoginRequest.LOGIN_TYPE
	0,  // 2: msg.LoginReply.error:type_name -> msg.ERROR_CODE
	1,  // 3: msg.Item.itemType:type_name -> msg.ITEM_TYPE
	2,  // 4: msg.Item.itemCategory:type_name -> msg.ITEM_CATEGORY
	0,  // 5: msg.LoadGameDataReply.error:type_name -> msg.ERROR_CODE
	10, // 6: msg.LoadGameDataReply.items:type_name -> msg.Item
	11, // 7: msg.LoadGameDataReply.mercenaries:type_name -> msg.Mercenary
	12, // 8: msg.LoadGameDataReply.stage:type_name -> msg.Stage
	13, // 9: msg.LoadGameDataReply.upgradePlayer:type_name -> msg.UpgradePlayer
	10, // 10: msg.SaveGameDataRequest.items:type_name -> msg.Item
	11, // 11: msg.SaveGameDataRequest.mercenaries:type_name -> msg.Mercenary
	12, // 12: msg.SaveGameDataRequest.stage:type_name -> msg.Stage
	13, // 13: msg.SaveGameDataRequest.upgradePlayer:type_name -> msg.UpgradePlayer
	0,  // 14: msg.SaveGameDataReply.error:type_name -> msg.ERROR_CODE
	0,  // 15: msg.RankingReply.error:type_name -> msg.ERROR_CODE
	0,  // 16: msg.RankingListReply.error:type_name -> msg.ERROR_CODE
	22, // 17: msg.RankingListReply.myRanking:type_name -> msg.RankingListReply.Ranking
	22, // 18: msg.RankingListReply.rankings:type_name -> msg.RankingListReply.Ranking
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_rpc_service_proto_init() }
func file_rpc_service_proto_init() {
	if File_rpc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcServiceExampleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcServiceExampleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mercenary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadGameDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadGameDataReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveGameDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveGameDataReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankingListReply_Ranking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_service_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_service_proto_goTypes,
		DependencyIndexes: file_rpc_service_proto_depIdxs,
		EnumInfos:         file_rpc_service_proto_enumTypes,
		MessageInfos:      file_rpc_service_proto_msgTypes,
	}.Build()
	File_rpc_service_proto = out.File
	file_rpc_service_proto_rawDesc = nil
	file_rpc_service_proto_goTypes = nil
	file_rpc_service_proto_depIdxs = nil
}
