// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rpc_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yyb {

  /// <summary>Holder for reflection information generated from rpc_service.proto</summary>
  public static partial class RpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for rpc_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFycGNfc2VydmljZS5wcm90bxIDeXliImAKGFJwY1NlcnZpY2VFeGFtcGxl",
            "UmVxdWVzdBIMCgRhcmcxGAEgASgFEgwKBGFyZzIYAiABKAISDAoEYXJnMxgD",
            "IAEoCRIMCgRhcmc0GAQgASgIEgwKBGFyZzUYBSADKAUiJwoWUnBjU2Vydmlj",
            "ZUV4YW1wbGVSZXBseRINCgVlcnJvchgBIAEoCSIHCgVFbXB0eSIjChBQdXNo",
            "Tm90aWZpY2F0aW9uEg8KB3BheWxvYWQYASABKAkiywEKDExvZ2luUmVxdWVz",
            "dBIvCglsb2dpblR5cGUYASABKA4yHC55eWIuTG9naW5SZXF1ZXN0LkxPR0lO",
            "X1RZUEUSEAoIbG9naW5LZXkYAiABKAkSDwoHaWRUb2tlbhgDIAEoCRIQCghu",
            "aWNrTmFtZRgEIAEoCSJVCgpMT0dJTl9UWVBFEhcKE0xPR0lOX1RZUEVfTk9O",
            "X0NFUlQQABIVChFMT0dJTl9UWVBFX0dPT0dMRRABEhcKE0xPR0lOX1RZUEVf",
            "RkFDRUJPT0sQAiKdBAoKTG9naW5SZXBseRIpCgVlcnJvchgBIAEoDjIaLnl5",
            "Yi5Mb2dpblJlcGx5LkVSUk9SX0NPREUSCwoDdXNuGAIgASgFEhAKCG5pY2tO",
            "YW1lGAMgASgJEhAKCGxvZ2luS2V5GAQgASgJEhEKCWFjY2Vzc0tleRgFIAEo",
            "CSKfAwoKRVJST1JfQ09ERRIRCg1FUlJPUl9DT0RFX09LEAASHQoZRVJST1Jf",
            "Q09ERV9FTVBUWV9OSUNLTkFNRRABEhsKF0VSUk9SX0NPREVfRFVQX05JQ0tO",
            "QU1FEAISLworRVJST1JfQ09ERV9OSUNLTkFNRV9IQVZFX1NQRUNJQUxfQ0hB",
            "UkFDVEVSUxADEiQKIEVSUk9SX0NPREVfVU5BQkxFX1RPX0NSRUFURV9VU0VS",
            "EAQSKgomRVJST1JfQ09ERV9GQUlMRURfVE9fQUNRVUlSRV9VU0VSX0lORk8Q",
            "BRIhCh1FUlJPUl9DT0RFX0dPT0dMRV9BVVRIX0ZBSUxFRBAGEh0KGUVSUk9S",
            "X0NPREVfRU1QVFlfSURfVE9LRU4QBxIpCiVFUlJPUl9DT0RFX0ZBSUxFRF9U",
            "T19VUERBVEVfTE9HSU5fS0VZEAgSKgomRVJST1JfQ09ERV9GQUlMRURfVE9f",
            "Q0hBTkdFX0xPR0lOX1RZUEUQCRImCiJFUlJPUl9DT0RFX0xPR0lOX1RZUEVf",
            "SVNfRElGRkVSRU5UEAoyvwEKClJwY1NlcnZpY2USUQoRUnBjU2VydmljZUV4",
            "YW1wbGUSHS55eWIuUnBjU2VydmljZUV4YW1wbGVSZXF1ZXN0GhsueXliLlJw",
            "Y1NlcnZpY2VFeGFtcGxlUmVwbHkiABIvCgZMaXN0ZW4SCi55eWIuRW1wdHka",
            "FS55eWIuUHVzaE5vdGlmaWNhdGlvbiIAMAESLQoFTG9naW4SES55eWIuTG9n",
            "aW5SZXF1ZXN0Gg8ueXliLkxvZ2luUmVwbHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.RpcServiceExampleRequest), global::Yyb.RpcServiceExampleRequest.Parser, new[]{ "Arg1", "Arg2", "Arg3", "Arg4", "Arg5" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.RpcServiceExampleReply), global::Yyb.RpcServiceExampleReply.Parser, new[]{ "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.Empty), global::Yyb.Empty.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.PushNotification), global::Yyb.PushNotification.Parser, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.LoginRequest), global::Yyb.LoginRequest.Parser, new[]{ "LoginType", "LoginKey", "IdToken", "NickName" }, null, new[]{ typeof(global::Yyb.LoginRequest.Types.LOGIN_TYPE) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Yyb.LoginReply), global::Yyb.LoginReply.Parser, new[]{ "Error", "Usn", "NickName", "LoginKey", "AccessKey" }, null, new[]{ typeof(global::Yyb.LoginReply.Types.ERROR_CODE) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RpcServiceExampleRequest : pb::IMessage<RpcServiceExampleRequest> {
    private static readonly pb::MessageParser<RpcServiceExampleRequest> _parser = new pb::MessageParser<RpcServiceExampleRequest>(() => new RpcServiceExampleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcServiceExampleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleRequest(RpcServiceExampleRequest other) : this() {
      arg1_ = other.arg1_;
      arg2_ = other.arg2_;
      arg3_ = other.arg3_;
      arg4_ = other.arg4_;
      arg5_ = other.arg5_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleRequest Clone() {
      return new RpcServiceExampleRequest(this);
    }

    /// <summary>Field number for the "arg1" field.</summary>
    public const int Arg1FieldNumber = 1;
    private int arg1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Arg1 {
      get { return arg1_; }
      set {
        arg1_ = value;
      }
    }

    /// <summary>Field number for the "arg2" field.</summary>
    public const int Arg2FieldNumber = 2;
    private float arg2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Arg2 {
      get { return arg2_; }
      set {
        arg2_ = value;
      }
    }

    /// <summary>Field number for the "arg3" field.</summary>
    public const int Arg3FieldNumber = 3;
    private string arg3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Arg3 {
      get { return arg3_; }
      set {
        arg3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "arg4" field.</summary>
    public const int Arg4FieldNumber = 4;
    private bool arg4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Arg4 {
      get { return arg4_; }
      set {
        arg4_ = value;
      }
    }

    /// <summary>Field number for the "arg5" field.</summary>
    public const int Arg5FieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_arg5_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> arg5_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Arg5 {
      get { return arg5_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcServiceExampleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcServiceExampleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Arg1 != other.Arg1) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Arg2, other.Arg2)) return false;
      if (Arg3 != other.Arg3) return false;
      if (Arg4 != other.Arg4) return false;
      if(!arg5_.Equals(other.arg5_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Arg1 != 0) hash ^= Arg1.GetHashCode();
      if (Arg2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Arg2);
      if (Arg3.Length != 0) hash ^= Arg3.GetHashCode();
      if (Arg4 != false) hash ^= Arg4.GetHashCode();
      hash ^= arg5_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Arg1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Arg1);
      }
      if (Arg2 != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Arg2);
      }
      if (Arg3.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Arg3);
      }
      if (Arg4 != false) {
        output.WriteRawTag(32);
        output.WriteBool(Arg4);
      }
      arg5_.WriteTo(output, _repeated_arg5_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Arg1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Arg1);
      }
      if (Arg2 != 0F) {
        size += 1 + 4;
      }
      if (Arg3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Arg3);
      }
      if (Arg4 != false) {
        size += 1 + 1;
      }
      size += arg5_.CalculateSize(_repeated_arg5_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcServiceExampleRequest other) {
      if (other == null) {
        return;
      }
      if (other.Arg1 != 0) {
        Arg1 = other.Arg1;
      }
      if (other.Arg2 != 0F) {
        Arg2 = other.Arg2;
      }
      if (other.Arg3.Length != 0) {
        Arg3 = other.Arg3;
      }
      if (other.Arg4 != false) {
        Arg4 = other.Arg4;
      }
      arg5_.Add(other.arg5_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Arg1 = input.ReadInt32();
            break;
          }
          case 21: {
            Arg2 = input.ReadFloat();
            break;
          }
          case 26: {
            Arg3 = input.ReadString();
            break;
          }
          case 32: {
            Arg4 = input.ReadBool();
            break;
          }
          case 42:
          case 40: {
            arg5_.AddEntriesFrom(input, _repeated_arg5_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RpcServiceExampleReply : pb::IMessage<RpcServiceExampleReply> {
    private static readonly pb::MessageParser<RpcServiceExampleReply> _parser = new pb::MessageParser<RpcServiceExampleReply>(() => new RpcServiceExampleReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcServiceExampleReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleReply(RpcServiceExampleReply other) : this() {
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcServiceExampleReply Clone() {
      return new RpcServiceExampleReply(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcServiceExampleReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcServiceExampleReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Error.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcServiceExampleReply other) {
      if (other == null) {
        return;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Error = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class PushNotification : pb::IMessage<PushNotification> {
    private static readonly pb::MessageParser<PushNotification> _parser = new pb::MessageParser<PushNotification>(() => new PushNotification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PushNotification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushNotification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushNotification(PushNotification other) : this() {
      payload_ = other.payload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PushNotification Clone() {
      return new PushNotification(this);
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 1;
    private string payload_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PushNotification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PushNotification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Payload != other.Payload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Payload.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PushNotification other) {
      if (other == null) {
        return;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Payload = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LoginRequest : pb::IMessage<LoginRequest> {
    private static readonly pb::MessageParser<LoginRequest> _parser = new pb::MessageParser<LoginRequest>(() => new LoginRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest(LoginRequest other) : this() {
      loginType_ = other.loginType_;
      loginKey_ = other.loginKey_;
      idToken_ = other.idToken_;
      nickName_ = other.nickName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest Clone() {
      return new LoginRequest(this);
    }

    /// <summary>Field number for the "loginType" field.</summary>
    public const int LoginTypeFieldNumber = 1;
    private global::Yyb.LoginRequest.Types.LOGIN_TYPE loginType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yyb.LoginRequest.Types.LOGIN_TYPE LoginType {
      get { return loginType_; }
      set {
        loginType_ = value;
      }
    }

    /// <summary>Field number for the "loginKey" field.</summary>
    public const int LoginKeyFieldNumber = 2;
    private string loginKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginKey {
      get { return loginKey_; }
      set {
        loginKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "idToken" field.</summary>
    public const int IdTokenFieldNumber = 3;
    private string idToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdToken {
      get { return idToken_; }
      set {
        idToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 4;
    private string nickName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginType != other.LoginType) return false;
      if (LoginKey != other.LoginKey) return false;
      if (IdToken != other.IdToken) return false;
      if (NickName != other.NickName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginType != 0) hash ^= LoginType.GetHashCode();
      if (LoginKey.Length != 0) hash ^= LoginKey.GetHashCode();
      if (IdToken.Length != 0) hash ^= IdToken.GetHashCode();
      if (NickName.Length != 0) hash ^= NickName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LoginType);
      }
      if (LoginKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LoginKey);
      }
      if (IdToken.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdToken);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NickName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LoginType);
      }
      if (LoginKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginKey);
      }
      if (IdToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdToken);
      }
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginRequest other) {
      if (other == null) {
        return;
      }
      if (other.LoginType != 0) {
        LoginType = other.LoginType;
      }
      if (other.LoginKey.Length != 0) {
        LoginKey = other.LoginKey;
      }
      if (other.IdToken.Length != 0) {
        IdToken = other.IdToken;
      }
      if (other.NickName.Length != 0) {
        NickName = other.NickName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LoginType = (global::Yyb.LoginRequest.Types.LOGIN_TYPE) input.ReadEnum();
            break;
          }
          case 18: {
            LoginKey = input.ReadString();
            break;
          }
          case 26: {
            IdToken = input.ReadString();
            break;
          }
          case 34: {
            NickName = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the LoginRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum LOGIN_TYPE {
        [pbr::OriginalName("LOGIN_TYPE_NON_CERT")] NonCert = 0,
        [pbr::OriginalName("LOGIN_TYPE_GOOGLE")] Google = 1,
        [pbr::OriginalName("LOGIN_TYPE_FACEBOOK")] Facebook = 2,
      }

    }
    #endregion

  }

  public sealed partial class LoginReply : pb::IMessage<LoginReply> {
    private static readonly pb::MessageParser<LoginReply> _parser = new pb::MessageParser<LoginReply>(() => new LoginReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Yyb.RpcServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply(LoginReply other) : this() {
      error_ = other.error_;
      usn_ = other.usn_;
      nickName_ = other.nickName_;
      loginKey_ = other.loginKey_;
      accessKey_ = other.accessKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReply Clone() {
      return new LoginReply(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private global::Yyb.LoginReply.Types.ERROR_CODE error_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Yyb.LoginReply.Types.ERROR_CODE Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "usn" field.</summary>
    public const int UsnFieldNumber = 2;
    private int usn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Usn {
      get { return usn_; }
      set {
        usn_ = value;
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 3;
    private string nickName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NickName {
      get { return nickName_; }
      set {
        nickName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "loginKey" field.</summary>
    public const int LoginKeyFieldNumber = 4;
    private string loginKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginKey {
      get { return loginKey_; }
      set {
        loginKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accessKey" field.</summary>
    public const int AccessKeyFieldNumber = 5;
    private string accessKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AccessKey {
      get { return accessKey_; }
      set {
        accessKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      if (Usn != other.Usn) return false;
      if (NickName != other.NickName) return false;
      if (LoginKey != other.LoginKey) return false;
      if (AccessKey != other.AccessKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Error != 0) hash ^= Error.GetHashCode();
      if (Usn != 0) hash ^= Usn.GetHashCode();
      if (NickName.Length != 0) hash ^= NickName.GetHashCode();
      if (LoginKey.Length != 0) hash ^= LoginKey.GetHashCode();
      if (AccessKey.Length != 0) hash ^= AccessKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Error != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Error);
      }
      if (Usn != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Usn);
      }
      if (NickName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NickName);
      }
      if (LoginKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LoginKey);
      }
      if (AccessKey.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AccessKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Error);
      }
      if (Usn != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Usn);
      }
      if (NickName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NickName);
      }
      if (LoginKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginKey);
      }
      if (AccessKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginReply other) {
      if (other == null) {
        return;
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      if (other.Usn != 0) {
        Usn = other.Usn;
      }
      if (other.NickName.Length != 0) {
        NickName = other.NickName;
      }
      if (other.LoginKey.Length != 0) {
        LoginKey = other.LoginKey;
      }
      if (other.AccessKey.Length != 0) {
        AccessKey = other.AccessKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Error = (global::Yyb.LoginReply.Types.ERROR_CODE) input.ReadEnum();
            break;
          }
          case 16: {
            Usn = input.ReadInt32();
            break;
          }
          case 26: {
            NickName = input.ReadString();
            break;
          }
          case 34: {
            LoginKey = input.ReadString();
            break;
          }
          case 42: {
            AccessKey = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the LoginReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ERROR_CODE {
        [pbr::OriginalName("ERROR_CODE_OK")] Ok = 0,
        [pbr::OriginalName("ERROR_CODE_EMPTY_NICKNAME")] EmptyNickname = 1,
        [pbr::OriginalName("ERROR_CODE_DUP_NICKNAME")] DupNickname = 2,
        [pbr::OriginalName("ERROR_CODE_NICKNAME_HAVE_SPECIAL_CHARACTERS")] NicknameHaveSpecialCharacters = 3,
        [pbr::OriginalName("ERROR_CODE_UNABLE_TO_CREATE_USER")] UnableToCreateUser = 4,
        [pbr::OriginalName("ERROR_CODE_FAILED_TO_ACQUIRE_USER_INFO")] FailedToAcquireUserInfo = 5,
        [pbr::OriginalName("ERROR_CODE_GOOGLE_AUTH_FAILED")] GoogleAuthFailed = 6,
        [pbr::OriginalName("ERROR_CODE_EMPTY_ID_TOKEN")] EmptyIdToken = 7,
        [pbr::OriginalName("ERROR_CODE_FAILED_TO_UPDATE_LOGIN_KEY")] FailedToUpdateLoginKey = 8,
        [pbr::OriginalName("ERROR_CODE_FAILED_TO_CHANGE_LOGIN_TYPE")] FailedToChangeLoginType = 9,
        [pbr::OriginalName("ERROR_CODE_LOGIN_TYPE_IS_DIFFERENT")] LoginTypeIsDifferent = 10,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
