// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc_service.proto

#include "rpc_service.pb.h"
#include "rpc_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace yyb {

static const char* RpcService_method_names[] = {
  "/yyb.RpcService/RpcServiceExample",
  "/yyb.RpcService/Login",
};

std::unique_ptr< RpcService::Stub> RpcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RpcService::Stub> stub(new RpcService::Stub(channel));
  return stub;
}

RpcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RpcServiceExample_(RpcService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(RpcService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RpcService::Stub::RpcServiceExample(::grpc::ClientContext* context, const ::yyb::RpcServiceExampleRequest& request, ::yyb::RpcServiceExampleReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RpcServiceExample_, context, request, response);
}

void RpcService::Stub::experimental_async::RpcServiceExample(::grpc::ClientContext* context, const ::yyb::RpcServiceExampleRequest* request, ::yyb::RpcServiceExampleReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RpcServiceExample_, context, request, response, std::move(f));
}

void RpcService::Stub::experimental_async::RpcServiceExample(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yyb::RpcServiceExampleReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RpcServiceExample_, context, request, response, std::move(f));
}

void RpcService::Stub::experimental_async::RpcServiceExample(::grpc::ClientContext* context, const ::yyb::RpcServiceExampleRequest* request, ::yyb::RpcServiceExampleReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RpcServiceExample_, context, request, response, reactor);
}

void RpcService::Stub::experimental_async::RpcServiceExample(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yyb::RpcServiceExampleReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RpcServiceExample_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::yyb::RpcServiceExampleReply>* RpcService::Stub::AsyncRpcServiceExampleRaw(::grpc::ClientContext* context, const ::yyb::RpcServiceExampleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yyb::RpcServiceExampleReply>::Create(channel_.get(), cq, rpcmethod_RpcServiceExample_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::yyb::RpcServiceExampleReply>* RpcService::Stub::PrepareAsyncRpcServiceExampleRaw(::grpc::ClientContext* context, const ::yyb::RpcServiceExampleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yyb::RpcServiceExampleReply>::Create(channel_.get(), cq, rpcmethod_RpcServiceExample_, context, request, false);
}

::grpc::Status RpcService::Stub::Login(::grpc::ClientContext* context, const ::yyb::LoginRequest& request, ::yyb::LoginReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void RpcService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::yyb::LoginRequest* request, ::yyb::LoginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void RpcService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yyb::LoginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void RpcService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::yyb::LoginRequest* request, ::yyb::LoginReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

void RpcService::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::yyb::LoginReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::yyb::LoginReply>* RpcService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::yyb::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yyb::LoginReply>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::yyb::LoginReply>* RpcService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::yyb::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::yyb::LoginReply>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

RpcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RpcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RpcService::Service, ::yyb::RpcServiceExampleRequest, ::yyb::RpcServiceExampleReply>(
          std::mem_fn(&RpcService::Service::RpcServiceExample), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RpcService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RpcService::Service, ::yyb::LoginRequest, ::yyb::LoginReply>(
          std::mem_fn(&RpcService::Service::Login), this)));
}

RpcService::Service::~Service() {
}

::grpc::Status RpcService::Service::RpcServiceExample(::grpc::ServerContext* context, const ::yyb::RpcServiceExampleRequest* request, ::yyb::RpcServiceExampleReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RpcService::Service::Login(::grpc::ServerContext* context, const ::yyb::LoginRequest* request, ::yyb::LoginReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yyb

