# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_service.proto',
  package='yyb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11rpc_service.proto\x12\x03yyb\"`\n\x18RpcServiceExampleRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x02\x12\x0c\n\x04\x61rg3\x18\x03 \x01(\t\x12\x0c\n\x04\x61rg4\x18\x04 \x01(\x08\x12\x0c\n\x04\x61rg5\x18\x05 \x03(\x05\"\'\n\x16RpcServiceExampleReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"#\n\x10PushNotification\x12\x0f\n\x07payload\x18\x01 \x01(\t\"0\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nserial_key\x18\x02 \x01(\t\"\x1b\n\nLoginReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t2\xbf\x01\n\nRpcService\x12Q\n\x11RpcServiceExample\x12\x1d.yyb.RpcServiceExampleRequest\x1a\x1b.yyb.RpcServiceExampleReply\"\x00\x12/\n\x06Listen\x12\n.yyb.Empty\x1a\x15.yyb.PushNotification\"\x00\x30\x01\x12-\n\x05Login\x12\x11.yyb.LoginRequest\x1a\x0f.yyb.LoginReply\"\x00\x62\x06proto3'
)




_RPCSERVICEEXAMPLEREQUEST = _descriptor.Descriptor(
  name='RpcServiceExampleRequest',
  full_name='yyb.RpcServiceExampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg1', full_name='yyb.RpcServiceExampleRequest.arg1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg2', full_name='yyb.RpcServiceExampleRequest.arg2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg3', full_name='yyb.RpcServiceExampleRequest.arg3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg4', full_name='yyb.RpcServiceExampleRequest.arg4', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg5', full_name='yyb.RpcServiceExampleRequest.arg5', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=122,
)


_RPCSERVICEEXAMPLEREPLY = _descriptor.Descriptor(
  name='RpcServiceExampleReply',
  full_name='yyb.RpcServiceExampleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='yyb.RpcServiceExampleReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=163,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='yyb.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=172,
)


_PUSHNOTIFICATION = _descriptor.Descriptor(
  name='PushNotification',
  full_name='yyb.PushNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='yyb.PushNotification.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=209,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='yyb.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yyb.LoginRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_key', full_name='yyb.LoginRequest.serial_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=259,
)


_LOGINREPLY = _descriptor.Descriptor(
  name='LoginReply',
  full_name='yyb.LoginReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='yyb.LoginReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=288,
)

DESCRIPTOR.message_types_by_name['RpcServiceExampleRequest'] = _RPCSERVICEEXAMPLEREQUEST
DESCRIPTOR.message_types_by_name['RpcServiceExampleReply'] = _RPCSERVICEEXAMPLEREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['PushNotification'] = _PUSHNOTIFICATION
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginReply'] = _LOGINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcServiceExampleRequest = _reflection.GeneratedProtocolMessageType('RpcServiceExampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCSERVICEEXAMPLEREQUEST,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.RpcServiceExampleRequest)
  })
_sym_db.RegisterMessage(RpcServiceExampleRequest)

RpcServiceExampleReply = _reflection.GeneratedProtocolMessageType('RpcServiceExampleReply', (_message.Message,), {
  'DESCRIPTOR' : _RPCSERVICEEXAMPLEREPLY,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.RpcServiceExampleReply)
  })
_sym_db.RegisterMessage(RpcServiceExampleReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.Empty)
  })
_sym_db.RegisterMessage(Empty)

PushNotification = _reflection.GeneratedProtocolMessageType('PushNotification', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFICATION,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.PushNotification)
  })
_sym_db.RegisterMessage(PushNotification)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREPLY,
  '__module__' : 'rpc_service_pb2'
  # @@protoc_insertion_point(class_scope:yyb.LoginReply)
  })
_sym_db.RegisterMessage(LoginReply)



_RPCSERVICE = _descriptor.ServiceDescriptor(
  name='RpcService',
  full_name='yyb.RpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=291,
  serialized_end=482,
  methods=[
  _descriptor.MethodDescriptor(
    name='RpcServiceExample',
    full_name='yyb.RpcService.RpcServiceExample',
    index=0,
    containing_service=None,
    input_type=_RPCSERVICEEXAMPLEREQUEST,
    output_type=_RPCSERVICEEXAMPLEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Listen',
    full_name='yyb.RpcService.Listen',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PUSHNOTIFICATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='yyb.RpcService.Login',
    index=2,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPCSERVICE)

DESCRIPTOR.services_by_name['RpcService'] = _RPCSERVICE

# @@protoc_insertion_point(module_scope)
